import os
import time

def firstRound():
    os.system('adb shell input tap 470 870')
    print('英灵1技能3')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)
    os.system('adb shell input tap 300 870')
    print('英灵1技能2')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)
    os.system('adb shell input tap 150 870')
    print('英灵1技能1')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)

    os.system('adb shell input tap 640 850')
    print('英灵2技能1')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)

    os.system('adb shell input tap 1130 860')
    print('英灵3技能1')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(0.3)
    os.system('adb shell input tap 580 700')
    print('选择对象英灵1')
    time.sleep(2)
    os.system('adb shell input tap 1400 860')
    print('英灵3技能3')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)

    os.system('adb shell input tap 1860 470')
    print('开启御主技能')
    time.sleep(0.3)
    os.system('adb shell input tap 1400 450')
    print('选择御主技能1')
    time.sleep(0.3)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)

    os.system('adb shell input tap 1770 920')
    print('Attack')
    time.sleep(1)
    os.system('adb shell input tap 678 349')
    print('选择大招1')
    time.sleep(0.2)
    os.system('adb shell input tap 650 750')
    print('选择卡牌2')
    time.sleep(0.2)
    os.system("adb shell input tap 1450 780")
    print('选择卡牌4')
    #过渡时间26s  预计30s
    time.sleep(33)    


def secondRound():
    os.system('adb shell input tap 1860 470')
    print('开启御主技能')
    time.sleep(0.3)
    os.system('adb shell input tap 1700 488')
    print('选择御主技能3')
    time.sleep(0.3)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(0.5)
    os.system('adb shell input tap 270 520')
    print('选择对象英灵1')
    time.sleep(0.5)
    os.system('adb shell input tap 1200 500')
    print('选择对象英灵4')
    time.sleep(0.5)
    os.system('adb shell input tap 1000 940')
    print('进行更替')
    time.sleep(6)

    #os.system('adb shell input tap 320 870')
    #print('英灵1技能2')
    #time.sleep(0.5)
    os.system('adb shell input tap 150 870')
    print('英灵1技能1')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)
    os.system('adb shell input tap 470 870')
    print('英灵1技能3')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(3)
    os.system('adb shell input tap 1260 880')
    print('英灵3技能2')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(3)

    os.system('adb shell input tap 1770 920')
    print('Attack')
    time.sleep(1)
    os.system('adb shell input tap 678 349')
    print('选择大招1')
    time.sleep(0.2)
    os.system('adb shell input tap 650 750')
    print('选择卡牌2')
    time.sleep(0.2)
    os.system("adb shell input tap 1450 780")
    print('选择卡牌4')
    #过渡时间26s  预计30s
    time.sleep(33)

def thirdRound():    
    os.system('adb shell input tap 760 870')
    print('英灵2技能2')
    time.sleep(0.5)
    os.system('adb shell input tap 1350 630')
    print('技能确定')
    time.sleep(2)

    os.system('adb shell input tap 1770 920')
    print('Attack')
    time.sleep(1)
    os.system('adb shell input tap 1027 320')
    print('选择大招2')
    time.sleep(0.2)
    os.system('adb shell input tap 650 750')
    print('选择卡牌2')
    time.sleep(0.2)
    os.system("adb shell input tap 1450 780")
    print('选择卡牌4')
    #过渡时间23s  预计25s
    time.sleep(30)

def main():
    print('This is saber caster team ready to make the world a better place.')
    firstRound()
    secondRound()
    thirdRound()

